### ISSUE TITLE
Post 2.0.0-rc.2 release activites

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#1250]
+ [x] Bump version number to 2.0.0-rc.3 https://github.com/FLAMEGPU/FLAMEGPU2/pull/1257
+ [x] Update tutorial
+ [x] Update c++ template repo
+ [ ] Maybe update python template repo - readme is old, maybe breaking changes?
+ [ ] Update other standalone repositories (#1222) and check README's are up to date
+ [ ] Fixup #1228 and merge to prevent future CI issues
+ [ ] Fix wheelhouse CI in advance of the next release https://github.com/FLAMEGPU/FLAMEGPU2-wheelhouse/issues/4

We should then consider what needs addressing / prioritising for the next release. Maybe setup a board / use a milestone?

Some thoughts:

+ #1150 
  - CUDA 12.2+ bad rtc perf, including the google colab tutorial
  - Requires nagging @benbarsdell to merge his stale PR (https://github.com/NVIDIA/jitify/pull/131), or forking Jitify
+ #1155 
  - better support, drops a cuda version so ideally pre-release
+ #1182
  - Python native example doesn't run because of this
+ #1235, #1236
  - Python version support changes
+ #1223
+ #710
+ #959 
+ #1237
  - Requested by David Fletcher

**Comment by Robadob** [comment]
Have now updated

https://github.com/FLAMEGPU/FLAMEGPU2-tutorial-python (both `main` and `gh-pages` branches)
https://github.com/FLAMEGPU/FLAMEGPU2-worked-example
https://github.com/FLAMEGPU/FLAMEGPU2-pedestrian_navigation-example
https://github.com/FLAMEGPU/FLAMEGPU2-tutorial-cudacpp
https://github.com/FLAMEGPU/FLAMEGPU2-model-template-cpp

I don't think Python template NEEDS updating (it's readme says python 3.7 though).

Likewise, benchmark repo's would probably want results updating if version was to be updated, for correctness.
